### ISSUE TITLE
Parser must be a string or character stream, not NoneType

### ISSUE THREAD

**Issue by chris-schmid** [singer-io/tap-recharge#20]
We're having issues extracting from certain endpoints via Stitch. Endpoints like addresses, charges, orders, onetimes, and subscriptions give an error like in the subject line. Meanwhile we can successfully replicate data from other endpoints like customers, products, the metafields endpoints, and shop.

The full logs from a recent failed extract of orders (along with a successful extract of some other endpoints) is attached. 

[stitch_recharge_extract_2021_11_19.txt](https://github.com/singer-io/tap-recharge/files/7571406/stitch_recharge_extract_2021_11_19.txt)

The only difference I can find between the successful and failing extractions are those that succeed don't have any records where updated_at is null, whereas those that fail DO have some records where updated_at is null.

Is it a requirement that updated_at is never null in order to use the recharge tap in Stitch? If not, anyone have ideas on what may be causing the extraction errors for certain endpoints?

**Comment by brperry10** [comment]
The have had the same issue, beginning in late October. Same "Parser must be a string or character stream, not NoneType" error message upon attempted extracts.

**Comment by MonikaRM** [comment]
I am also facing this "Parser must be a string or character stream, not NoneType"  with addresses,  orders and onetimes.
Hello @chris-schmid @brperry10 , do we found any solution?

**Comment by MonikaRM** [comment]
Can we handle this problem by handling the nonetype value in the main code?. I was thinking that method but then I am not sure that the data is available at updated_at=None. As we are getting updated_at as none that is the reason of throwing the parser error.

**Comment by savan-chovatiya** [comment]
@chris-schmid . The mentioned issue is already resolved as part of #25  so can we close this issue?
