### ISSUE TITLE
Subscription Table Replication Strategy

### ISSUE THREAD

**Issue by austinhutchison** [singer-io/tap-recharge#7]
I didn't realize the incremental replication strategy for Subscriptions table would mean that the `next_charge_scheduled_at` is not updated. 

> ~~Does that also mean that columns like `status` are not updated on extractions/loads as well?~~

Okay I confirmed these rows are updated despite incremental replication. Is there something special about `next_charge_scheduled_at` that causes it to not reflect the API value?

> ~~Should the Subscriptions table be slated for full replication?~~

Seems like the issue is specifically with `next_charge_scheduled_at`

**Comment by aviwebberman** [comment]
When a subscription's `next_charge_scheduled_at` value changes, I don't think it gets reflected as an update in the Recharge API when pulling new subscriptions filtered on `updated_at` (so the updated subscription doesn't get pulled in at all even though it has technically been modified). As far as I know this is just an issue with `next_charge_scheduled_at`, but not positive.

**Comment by austinhutchison** [comment]
@aviwebberman that makes sense! I think this might be an issue with the ReCharge API. Thanks for taking a look :) I'll mark this as closed
